cssite/collect/urls.py
from django.urls import path
from . import views


app_name = "collect"
urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('userinfo/', views.userinfo, name='userinfo'),
    path('update/<int:pk>/', views.update, name='update'),
    path('delete/<int:pk>/', views.delete, name='delete'),
    path('tasks/', views.TaskList.as_view(), name='tasks'),
    path('tasks/<int:pk>/', views.TaskDetail.as_view(), name='task-detail'),
    path('participations/', views.ParticipationList.as_view(), name='participations'),
    path('tasks/<int:pk>/create/', views.create_participation, name='create-participation'),
    path('participations/<int:pk>/delete/', views.delete_participation, name='delete-participation'),
    path('tasks/<int:pk>/parsedfiles/', views.ParsedfileList.as_view(), name='submitted-parsedfiles'),
    path('graded-parsedfiles/', views.GradedfileList.as_view(), name='graded-parsedfiles'),
    path('allocated-parsedfiles/', views.AllocatedfileList.as_view(), name='allocated-parsedfiles'),
    path('allocated-parsedfiles/<int:pk>/', views.grade_parsedfile, name='grade-parsedfile'),
    path('users/', views.UserList.as_view(), name='users'),
    path('users/<int:pk>', views.UserDetail.as_view(), name='user-detail'),
]

cssite/cssite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('collect/', include('collect.urls')),
]

cssite/collect/models.py
from django import forms
from django.db import models
from django.contrib.auth.models import User 
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ObjectDoesNotExist


class Account(models.Model):
    GENDER_CHOICES = [
        ('남성', '남성'),
        ('여성', '여성'),
    ]
    
    ROLE_CHOICES = [
        ('제출자', '제출자'),
        ('평가자', '평가자'),
        ('관리자', '관리자'),
    ]

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField('이름', max_length=20)
    contact = models.CharField('연락처', max_length=20)
    birth = models.DateField('생년월일', null=True, blank=True)
    gender = models.CharField('성별', max_length=5, choices=GENDER_CHOICES)
    address = models.CharField('주소', max_length=100)
    role = models.CharField('역할', max_length=10, choices=ROLE_CHOICES)

    def __str__(self):
        return self.role
    

class Task(models.Model):
    name = models.CharField('태스크 이름', max_length=45, unique=True)
    minimal_upload_frequency = models.CharField('최소 업로드 주기', max_length=45)
    activation_state = models.BooleanField('활성화 상태', default=True)
    description = models.CharField('태스크 설명', max_length=100)
    original_data_description = models.CharField('원본 데이터 설명', max_length=100)

    def __str__(self):
        return self.name


class Participation(models.Model):
    class Meta:
        unique_together = (('account', 'task'),)

    account = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='participations', verbose_name='제출자')
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='participations', verbose_name='태스크')
    admission = models.BooleanField('승인 상태', default=False)
    submit_count = models.IntegerField('제출 횟수', default=0)


def grading_score_validator(value):
    if value < 0 or value > 10:
        raise forms.ValidationError('0 ~ 10 사이의 숫자를 입력해주세요.')


class ParsedFile(models.Model):
    submitter = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='parsed_submits', verbose_name='제출자')
    grader = models.ForeignKey(Account, on_delete=models.CASCADE, related_name='parsed_grades', verbose_name='평가자', null=True, blank=True)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='parsedfiles', verbose_name='태스크')
    directory = models.CharField('파일 경로', max_length=200)
    submit_number = models.IntegerField('제출 회차')
    start_date = models.DateField('시작 날짜')
    end_date = models.DateField('종료 날짜')
    total_tuple = models.IntegerField('전체 튜플 수')
    duplicated_tuple = models.IntegerField('중복 튜플 수')
    null_ratio = models.FloatField('null 비율')
    grading_score = models.IntegerField('평가 점수', null=True, blank=True, validators=[grading_score_validator])
    pass_state = models.BooleanField('패스 여부', null=True, blank=True)
    grading_end_date = models.DateField('평가 종료 날짜')
    grade_date = models.DateField('평가 날짜', auto_now=True)

    def __str__(self):
        return self.directory


class MappingInfo(models.Model):
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='mapping_infos', verbose_name='태스크')
    orginal_schema_name = models.CharField('원본 스키마 이름', max_length=45)
    orginal_column_name = models.CharField('원본 스키마 속성 레이블', max_length=45)
    parsing_column_name = models.CharField('파싱 스키마 속성 레이블', max_length=45)

    def __str__(self):
        return self.orginal_schema_name

cssite/collect/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Account, Task, ParsedFile, Participation, MappingInfo


class LoginForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class GradeForm(forms.ModelForm):
    pass_state = forms.BooleanField(required=False)
    class Meta:
        model = ParsedFile
        fields = ['grading_score', 'pass_state']

cssite/collect/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.urls import reverse
from django.views import generic, View
from django.contrib import auth
from django.contrib.auth.models import User
from .models import Account, Task, Participation, ParsedFile, MappingInfo
from .forms import LoginForm, GradeForm
from datetime import date


# 홈
def index(request):
    return render(request, 'collect/index.html')


# 회원가입
def signup(request):
    context = {}
    if request.method == "POST":
        if request.POST["password1"] == request.POST["password2"]:
            user = User.objects.create_user(
                username=request.POST["username"],
                password=request.POST["password1"])
            account = Account(
                user=user,
                name=request.POST["name"],
                contact = request.POST["contact"],
                birth = request.POST["birth"],
                gender = request.POST["gender"],
                address = request.POST["address"],
                role = request.POST["role"])
            account.save()
            auth.login(request, user)
            if account.role == '제출자':
                return redirect(reverse('collect:tasks'))
            elif account.role == '평가자':
                return redirect(reverse('collect:allocated-parsedfiles'))
        else:
            context.update({'error':"비밀번호가 일치하지 않습니다."})
    return render(request, 'collect/signup.html', context)


# 로그인
def login(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            if user.account.role == '제출자':
                return redirect(reverse('collect:tasks'))
            elif user.account.role == '평가자':
                return redirect(reverse('collect:allocated-parsedfiles'))
            else:
                return redirect(reverse('collect:users'))
        return HttpResponse('로그인 실패. 다시 시도 해보세요.')
    else:
        form = LoginForm()
        return render(request, 'collect/login.html', {'form':form})


# 로그아웃
def logout(request):
    auth.logout(request)
    return redirect(reverse('collect:index'))


# 정보 조회
def userinfo(request, pk):
    user = request.user
    account = user.account
    context = {
        'user': user,
        'account': account
    }
    return render(request, 'collect/userinfo.html', context)


# 회원 정보 수정
def update(request, pk):
    if request.method == "POST":
        user = request.user
        if request.POST["password1"] == request.POST["password2"]:
            user.set_password(request.POST["password1"])
            user.save()
            account = user.account
            account.name=request.POST["name"]
            account.contact = request.POST["contact"]
            account.birth = request.POST["birth"]
            account.gender = request.POST["gender"]
            account.address = request.POST["address"]
            account.save()
            auth.login(request, user)
            if account.role == '제출자':
                return redirect(reverse('collect:tasks'))
            elif account.role == '평가자':
                return redirect(reverse('collect:allocated-parsedfiles'))
    return render(request, 'collect/update.html')

# 회원 탈퇴
def delete(request, pk):
    user = User.objects.get(pk=pk)
    user.delete()
    return redirect(reverse('collect:index'))


# 태스크 목록
class TaskList(View):
    def get(self, request):
        account = request.user.account
        task_list = Task.objects.all()
        participations = Participation.objects.filter(account=account)
        participate_tasks = [participation.task for participation in participations]
        context = {
            'task_list': task_list,
            'participate_tasks': participate_tasks
        }
        return render(request, 'collect/task.html', context)


# 태스크 상세 정보
class TaskDetail(generic.DetailView):
    model = Task
    context_object_name = 'task'
    template_name = 'collect/task_detail.html'


# 태스크 참여
def create_participation(request, pk):
    user = request.user
    task = get_object_or_404(Task, pk=pk)
    participation = Participation(account=user.account, task=task)
    participation.save()
    return redirect(reverse('collect:participations'))


# 참여 중인 태스크 목록
class ParticipationList(View):
    def get(self, request):
        user = request.user
        participations = user.account.participations.all()
        return render(request, 'collect/participation.html', {'participations': participations})


# 태스크 참여 취소, 관리자 승인
def delete_participation(request, pk):
    if request.user.is_superuser:
        participation = get_object_or_404(Participation, pk=pk)
        participation.admission = True
        participation.save()
        return redirect(reverse('collect:users'))
    else:
        participation = get_object_or_404(Participation, pk=pk)
        participation.delete()
        return redirect(reverse('collect:participations'))


# 제출한 파일 목록
class ParsedfileList(View):
    def get(self, request, pk):
        user = request.user
        task = get_object_or_404(Task, pk=pk)
        parsedfile_list = user.account.parsed_submits.filter(task=task)
        total_tuple = sum(parsedfile.total_tuple for parsedfile in parsedfile_list)
        context = {
            'task': task,
            'parsedfile_list': parsedfile_list,
            'total_tuple': total_tuple
        }
        return render(request, 'collect/submitted_parsedfile.html', context)


# 평가된 파일 목록
class GradedfileList(View):
    def get(self, request):
        user = request.user
        parsedfiles = user.account.parsed_grades.filter(grading_score__isnull=False)
        return render(request, 'collect/graded_parsedfile.html', {'parsedfiles': parsedfiles})


# 할당된 파일 목록
class AllocatedfileList(View):
    def get(self, request):
        user = request.user
        parsedfiles = user.account.parsed_grades.filter(grading_score__isnull=True)
        now = date.today()
        context = {
            'parsedfiles': parsedfiles,
            'now': now
        }
        return render(request, 'collect/allocated_parsedfile.html', context)


# 파일 평가
def grade_parsedfile(request, pk):
    if request.method == "POST":
        form = GradeForm(request.POST)
        parsedfile = get_object_or_404(ParsedFile, pk=pk)
        if form.is_valid():
            parsedfile.grading_score = form.cleaned_data['grading_score']
            parsedfile.pass_state = form.cleaned_data['pass_state']
            parsedfile.save()
            return redirect(reverse('collect:graded-parsedfiles'))
        context = {
            'form': form,
            'parsedfile': parsedfile
        }
        context.update({'error':'0 ~ 10 사이의 숫자를 입력해주세요.'})
        return render(request, 'collect/grade.html', context)
    else:
        form = GradeForm()
        parsedfile = get_object_or_404(ParsedFile, pk=pk)
        context = {
            'form': form,
            'parsedfile': parsedfile
        }
        return render(request, 'collect/grade.html', context)

# 유저 검색
class UserList(View):
    def get(self, request):
        tasks = Task.objects.all()
        accounts = Account.objects.all()
        username = request.GET.get('username')
        gender = request.GET.get('gender')
        role = request.GET.get('role')
        birth1 = request.GET.get('birth1')
        birth2 = request.GET.get('birth2')
        taskname = request.GET.get('taskname')
        if username:
            accounts = accounts.filter(user__username__contains=username)
        if gender:
            accounts = accounts.filter(gender__exact=gender)
        if role:
            accounts = accounts.filter(role__exact=role)
        if birth1 and birth2:
            accounts = accounts.filter(birth__range=(birth1, birth2))
        if taskname:
            task = Task.objects.get(name=taskname)
            accounts = accounts.filter(participations__in=task.participations.all())
        context = {
            'accounts': accounts,
            'tasks': tasks
        }
        return render(request, 'collect/userlist.html', context)


# 유저 상세 정보
class UserDetail(View):
    def get(self, request, pk):
        user = User.objects.get(pk=pk)
        if user.account.role == '제출자':
            participations = user.account.participations.all()
            return render(request, 'collect/participation.html', {'participations': participations})
        elif user.account.role == '평가자':
            user = User.objects.get(pk=pk)
            parsedfiles = user.account.parsed_grades.filter(grading_score__isnull=False)
            return render(request, 'collect/graded_parsedfile.html', {'parsedfiles': parsedfiles})

cssite/collect/templates/collect/allocated_parsedfile.html
<a href="{% url 'collect:graded-parsedfiles' %}">내 평가 기록</a>
<h1>할당된 파일 목록</h1>
<ul>
{% for parsedfile in parsedfiles %}
    <li>
        {{ parsedfile.task.name }} {{ parsedfile.directory }}
        {% if parsedfile.grading_end_date > now %}
            <a href="{% url 'collect:grade-parsedfile' parsedfile.id %}">평가하기</a>
        {% else %}
            평가 기간 만료
        {% endif %}
    </li>
{% endfor %}
</ul>

cssite/collect/templates/collect/grade.html
<h2>평가하기</h2>
<form action="{% url 'collect:grade-parsedfile' parsedfile.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="완료">
</form>

cssite/collect/templates/collect/graded_parsedfile.html
<h1>평가된 파일 목록</h1>
<ul>
{% for parsedfile in parsedfiles %}
    <li>
        {{ parsedfile.task.name }} {{ parsedfile.directory }} {{ parsedfile.grade_date }} {{ parsedfile.grading_score }}
        {% if parsedfile.pass_state %}
            Pass
        {% else %}
            NonPass
        {% endif %}
    </li>
{% endfor %}
</ul>

cssite/collect/templates/collect/index.html
{% if user.is_authenticated %}
    <a href="{% url 'collect:logout' %}">로그아웃</a>
    <a href="{% url 'collect:update' user.id %}">정보 수정</a>
    <a href="{% url 'collect:delete' user.id %}">회원 탈퇴</a>
{% else %}
    <a href="{% url 'collect:login' %}">로그인</a>
{% endif %}
<a href="{% url 'collect:signup' %}">회원가입</a>

cssite/collect/templates/collect/login.html
<h2>로그인</h2>
<form action="{% url 'collect:login' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="로그인">
</form>

cssite/collect/templates/collect/parsedfile.html
<h1>내가 제출한 파일 목록</h1>
태스크 이름: {{ task.name }}<br>
저장된 tuple 수: {{ total_tuple }}
<p>파일 이름-회차-기간-평가 점수-패스 여부</p>
<ul>
{% for parsedfile in parsedfile_list %}
    <li>
    {{ parsedfile.directory }} {{ parsedfile.submit_number }} {{ parsedfile.start_date }}~{{ parsedfile.end_date }}
    {{ parsedfile.grading_score }} {{ parsedfile.pass_state }}
    </li>
{% endfor %}
</ul>

cssite/collect/templates/collect/participation.html
<h1>참여 신청 중인 태스크 목록</h1>
<p>태스크 이름-참여 상태-참여 신청</p>
<ul>
{% for participate in participations %}
    {% if not participate.admission %}
    <li>
        <a href="{% url 'collect:task-detail' participate.task.id %}">{{ participate.task.name }}</a>
        참여 신청 중
        {% if request.user.is_superuser %}
            <a href="{% url 'collect:delete-participation' participate.id %}">승인</a>
        {% else %}
            <a href="{% url 'collect:delete-participation' participate.id %}">취소</a>
        {% endif %}
    </li>
    {% endif %}
{% endfor %}
</ul>

<h1>참여 중인 태스크 목록</h1>
<p>태스크 이름-제출한 파일 수-상세조회</p>
<ul>
{% for participate in participations %}
    {% if participate.admission %}
    <li>
        <a href="{% url 'collect:task-detail' participate.task.id %}">{{ participate.task.name }}</a>
        {{ participate.submit_count }}
        <a href="{% url 'collect:submitted-parsedfiles' participate.task.id %}">상세조회</a>
    </li>
    {% endif %}
{% endfor %}
</ul>

cssite/collect/templates/collect/signup.html
<h2>회원가입</h2>
<form action="{% url 'collect:signup' %}" method="post">
    {% csrf_token %}
    아이디:
    <input type="text" name="username"><br>
    비밀번호:
    <input type="password" name="password1"><br>
    비밀번호 확인:
    <input type="password" name="password2"><br>
    이름:
    <input type="text" name="name"><br>
    연락처:
    <input type="text" name="contact"><br>
    생년월일:
    <input type="date" name="birth"><br>
    성별:
    <select name="gender">
        <option value="남성">남성</option>
        <option value="여성">여성</option>
    </select><br>
    주소:
    <input type="text" name="address"><br>
    역할:
    <select name="role">
        <option value="제출자">제출자</option>
        <option value="평가자">평가자</option>
    </select><br><br>
    <input type="submit" value="회원가입">
</form>

cssite/collect/templates/collect/submitted_parsedfile.html
<h1>제출한 파일 목록</h1>
태스크 이름: {{ task.name }}<br>
저장된 tuple 수: {{ total_tuple }}
<p>파일 이름-회차-기간-평가 점수-패스 여부</p>
<ul>
{% for parsedfile in parsedfile_list %}
    <li>
    {{ parsedfile.directory }} {{ parsedfile.submit_number }} {{ parsedfile.start_date }}~{{ parsedfile.end_date }}
    {{ parsedfile.grading_score }} {{ parsedfile.pass_state }}
    </li>
{% endfor %}
</ul>

cssite/collect/templates/collect/task.html
<a href="{% url 'collect:participations' %}">내 태스크 목록</a>
<h1>태스크 목록</h1>
<ul>
{% for task in task_list %}
    {% if task.activation_state %}
        <li>
            <a href="{% url 'collect:task-detail' task.id %}">{{ task.name }}</a>
            {% if task not in participate_tasks %}
                <a href="{% url 'collect:create-participation' task.id %}">참여 신청</a>
            {% else %}
                신청 완료
            {% endif %}
        </li>
    {% endif %}
{% endfor %}
</ul>

cssite/collect/templates/collect/task_detail.html
<h1>태스크 정보</h1>
<p>태스크 이름: {{ task.name }}</p>
<p>최소 업로드 주기: {{ task.minimal_upload_frequency }}</p>
<p>태스크 설명: {{ task.description }}</p>
<p>원본 데이터 설명: {{ task.original_data_description }}</p>

cssite/collect/templates/collect/update.html
<h2>회원 정보 수정</h2>
<form action="{% url 'collect:update' user.id %}" method="post">
    {% csrf_token %}
    비밀번호:
    <input type="password" name="password1"><br>
    비밀번호 확인:
    <input type="password" name="password2"><br>
    이름:
    <input type="text" name="name"><br>
    연락처:
    <input type="text" name="contact"><br>
    생년월일:
    <input type="date" name="birth"><br>
    성별:
    <select name="gender">
        <option value="남성">남성</option>
        <option value="여성">여성</option>
    </select><br>
    주소:
    <input type="text" name="address"><br>
    <input type="submit" value="수정">
</form>

cssite/collect/templates/collect/userlist.html
<form action="{% url 'collect:users' %}" method="get">
    아이디:
    <input type="text" name="username">
    성별:
    <select name="gender">
        <option value="">--</option>
        <option value="남성">남성</option>
        <option value="여성">여성</option>
    </select>
    역할:
    <select name="role">
        <option value="">--</option>
        <option value="제출자">제출자</option>
        <option value="평가자">평가자</option>
    </select>
    생년월일:
    <input type="date" name="birth1"> ~ <input type="date" name="birth2">
    참여 태스크:
    <select name="taskname">
        <option value="">--</option>
        {% for task in tasks %}
        <option value="{{ task.name }}">{{ task.name }}</option>
        {% endfor %}
    </select>
    <input type="submit" value="검색">
</form>

역할 ID 생년월일 성별 참여중인태스크 상세조회
<ul>
    {% for account in accounts %}
        {% if account.role != '관리자' %}
            <li>
            {{ account.role }} {{ account.user.username }} {{ account.birth }} {{ account.gender }}
            {% for participation in account.participations.all %}
                {% if participation.admission %}
                    {{ participation.task.name }} 
                {% endif %}
            {% endfor %}
            <a href="{% url 'collect:user-detail' account.user.id %}">상세조회</a>
            </li>
        {% endif %}
    {% endfor %}
</ul>